<!-- Notes:

Read this and follow the steps to organize and stuff.
https://medium.com/@caneuenschwander/how-to-turn-a-messy-jupyter-notebook-into-a-professional-python-project-f34d5ee7f88b



-->

<style>
  .text {
    white-space: pre;
  }
</style>

<div style="font-family:Times New Roman;float:center;"><p>What is the optimal graft choice for anterior cruciate ligament reconstruction surgery?</p></div>

<div align="center">
	<a href="https://dongwkim.com"><img src="logo.svg" alt="Logo" width="200" height="200"></a><br>
	<font size="20" style="font-family:Times New Roman;font-variant: small-caps;">  Network Meta-Analysis</font><br>
</div>

</div>	
<br>
<hline></hline>
<font size = "1em">
<sup>1</sup> Department of Anatomy, Jagiellonian University, Kraków, Poland  <br/>
<sup>2</sup> Whiting College of Engineering, Johns Hopkins University, Baltimore, MD, United States  <br/>
<sup>3</sup> Harvard Dataverse, Harvard University, Cambridge, MA, United States
</font>
</div>

<details>
    <summary>Table of Contents</summary>  
    
<a id="toc"></a>
    
- [Search strategy](#search-strategy)
- [Search](#search)
- [Deduplication](#deduplication)
- [Screening](#screening)
 
</details>

<details>
    <summary>Kanban</summary>  


```mermaid

kanban
  [Systematic review]
      id1[Protocol]
      id2[Search strategy]
      id3[Search]
      id4[Deduplication]
      id5[Screening]
  [Data]
      id6[Database]
      id7[Form]
      id8[Collection]
      id9[Transformation]
  [Meta-analysis]
      id10[Effect size pooling]
      id11[Subgroup analysis]
      id12[Forest plots]
      id13[Regression]
  [Manuscript]
      id14[Tables and Figures]
      id15[Results]
      id16[Methods]
      id17[Introduction]
      id18[Discussion]
      id19[Abstract]

```

</details>

<details>
    <summary>Flowchart</summary>
  
```mermaid
---
config:
  curve: stepBefore
---

graph LR

part1["systematic review"]
A["protocol"]
B["search strategy"]
C["search"]
D["deduplication"]
E["screening"]
E1["title and abstract<br>screening"]
E2["full-text screening"]

part2["data extraction"]
part3["meta-analysis"]

part1 --> A
A --> B
B --> C
C --> D
D --> E
E --> E1 & E2
E2 --> part2 --> part3
```

</details>

<details>
    <summary>Checklist</summary>

<table style="width:100%;">
<colgroup>
<col style="width: 21%" />
<col style="width: 6%" />
<col style="width: 59%" />
<col style="width: 12%" />
</colgroup>
<thead>
<tr>
<th style="text-align: center;"><strong>Section/Topic</strong></th>
<th style="text-align: center;"><strong>Item #</strong></th>
<th style="text-align: center;"><strong>Checklist Item</strong></th>
<th style="text-align: center;"><strong>Reported on Page #</strong></th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>TITLE</strong></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Title</p>
</blockquote></td>
<td>1</td>
<td>Identify the report as a systematic review <em>incorporating a
network meta-analysis (or related form of meta-analysis).</em></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td><strong>ABSTRACT</strong></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Structured summary</p>
</blockquote></td>
<td>2</td>
<td><p>Provide a structured summary including, as applicable:</p>
<blockquote>
<p><strong>Background:</strong> main objectives</p>
<p><strong>Methods:</strong> data sources; study eligibility criteria,
participants, and interventions; study appraisal; and <em>synthesis
methods, such as network meta-analysis.</em></p>
<p><strong>Results:</strong> number of studies and participants
identified; summary estimates with corresponding confidence/credible
intervals; <em>treatment rankings may also be discussed. Authors may
choose to summarize pairwise comparisons against a chosen treatment
included in their analyses for brevity.</em></p>
<p><strong>Discussion/Conclusions:</strong> limitations; conclusions and
implications of findings.</p>
<p><strong>Other:</strong> primary source of funding; systematic review
registration number with registry name.</p>
</blockquote></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td><strong>INTRODUCTION</strong></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Rationale</p>
</blockquote></td>
<td>3</td>
<td>Describe the rationale for the review in the context of what is
already known<em>, including mention of why a network meta-analysis has
been conducted.</em></td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Objectives</p>
</blockquote></td>
<td>4</td>
<td>Provide an explicit statement of questions being addressed, with
reference to participants, interventions, comparisons, outcomes, and
study design (PICOS).</td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td><strong>METHODS</strong></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Protocol and registration</p>
</blockquote></td>
<td>5</td>
<td>Indicate whether a review protocol exists and if and where it can be
accessed (e.g., Web address); and, if available, provide registration
information, including registration number.</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Eligibility criteria</p>
</blockquote></td>
<td>6</td>
<td>Specify study characteristics (e.g., PICOS, length of follow-up) and
report characteristics (e.g., years considered, language, publication
status) used as criteria for eligibility, giving rationale. <em>Clearly
describe eligible treatments included in the treatment network, and note
whether any have been clustered or merged into the same node (with
justification).</em></td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Information sources</p>
</blockquote></td>
<td>7</td>
<td>Describe all information sources (e.g., databases with dates of
coverage, contact with study authors to identify additional studies) in
the search and date last searched.</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Search</p>
</blockquote></td>
<td>8</td>
<td>Present full electronic search strategy for at least one database,
including any limits used, such that it could be repeated.</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Study selection</p>
</blockquote></td>
<td>9</td>
<td>State the process for selecting studies (i.e., screening,
eligibility, included in systematic review, and, if applicable, included
in the meta-analysis).</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Data collection process</p>
</blockquote></td>
<td>10</td>
<td>Describe method of data extraction from reports (e.g., piloted
forms, independently, in duplicate) and any processes for obtaining and
confirming data from investigators.</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Data items</p>
</blockquote></td>
<td>11</td>
<td>List and define all variables for which data were sought (e.g.,
PICOS, funding sources) and any assumptions and simplifications
made.</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p><strong>Geometry of the network</strong></p>
</blockquote></td>
<td><strong>S1</strong></td>
<td>Describe methods used to explore the geometry of the treatment
network under study and potential biases related to it. This should
include how the evidence base has been graphically summarized for
presentation, and what characteristics were compiled and used to
describe the evidence base to readers.</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Risk of bias within individual studies</p>
</blockquote></td>
<td>12</td>
<td>Describe methods used for assessing risk of bias of individual
studies (including specification of whether this was done at the study
or outcome level), and how this information is to be used in any data
synthesis.</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Summary measures</p>
</blockquote></td>
<td>13</td>
<td>State the principal summary measures (e.g., risk ratio, difference
in means). <em>Also describe the use of additional summary measures
assessed, such as treatment rankings and surface under the cumulative
ranking curve (SUCRA) values, as well as modified approaches used to
present summary findings from meta-analyses.</em></td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Planned methods of analysis</p>
</blockquote></td>
<td>14</td>
<td><p>Describe the methods of handling data and combining results of
studies for each network meta-analysis. This should include, but not be
limited to:</p>
<ul>
<li><p><em>Handling of multi-arm trials;</em></p></li>
<li><p><em>Selection of variance structure;</em></p></li>
<li><p><em>Selection of prior distributions in Bayesian analyses;
and</em></p></li>
<li><p><em>Assessment of model fit.</em></p></li>
</ul></td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p><strong>Assessment of Inconsistency</strong></p>
</blockquote></td>
<td><strong>S2</strong></td>
<td>Describe the statistical methods used to evaluate the agreement of
direct and indirect evidence in the treatment network(s) studied.
Describe efforts taken to address its presence when found.</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Risk of bias across studies</p>
</blockquote></td>
<td>15</td>
<td>Specify any assessment of risk of bias that may affect the
cumulative evidence (e.g., publication bias, selective reporting within
studies).</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Additional analyses</p>
</blockquote></td>
<td>16</td>
<td><p>Describe methods of additional analyses if done, indicating which
were pre-specified. This may include, but not be limited to, the
following:</p>
<ul>
<li><p>Sensitivity or subgroup analyses;</p></li>
<li><p>Meta-regression analyses;</p></li>
<li><p><em>Alternative formulations of the treatment network;
and</em></p></li>
<li><p><em>Use of alternative prior distributions for Bayesian analyses
(if applicable).</em></p></li>
</ul></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td><strong>RESULTS†</strong></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Study selection</p>
</blockquote></td>
<td>17</td>
<td>Give numbers of studies screened, assessed for eligibility, and
included in the review, with reasons for exclusions at each stage,
ideally with a flow diagram.</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p><strong>Presentation of network structure</strong></p>
</blockquote></td>
<td><strong>S3</strong></td>
<td>Provide a network graph of the included studies to enable
visualization of the geometry of the treatment network.</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p><strong>Summary of network geometry</strong></p>
</blockquote></td>
<td><strong>S4</strong></td>
<td>Provide a brief overview of characteristics of the treatment
network. This may include commentary on the abundance of trials and
randomized patients for the different interventions and pairwise
comparisons in the network, gaps of evidence in the treatment network,
and potential biases reflected by the network structure.</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Study characteristics</p>
</blockquote></td>
<td>18</td>
<td>For each study, present characteristics for which data were
extracted (e.g., study size, PICOS, follow-up period) and provide the
citations.</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Risk of bias within studies</p>
</blockquote></td>
<td>19</td>
<td>Present data on risk of bias of each study and, if available, any
outcome level assessment.</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Results of individual studies</p>
</blockquote></td>
<td>20</td>
<td>For all outcomes considered (benefits or harms), present, for each
study: 1) simple summary data for each intervention group, and 2) effect
estimates and confidence intervals. <em>Modified approaches may be
needed to deal with information from larger networks.</em></td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Synthesis of results</p>
</blockquote></td>
<td>21</td>
<td>Present results of each meta-analysis done, including
confidence/credible intervals. <em>In larger networks, authors may focus
on comparisons versus a particular comparator (e.g. placebo or standard
care), with full findings presented in an appendix. League tables and
forest plots may be considered to summarize pairwise comparisons.</em>
If additional summary measures were explored (such as treatment
rankings), these should also be presented.</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p><strong>Exploration for inconsistency</strong></p>
</blockquote></td>
<td><strong>S5</strong></td>
<td>Describe results from investigations of inconsistency. This may
include such information as measures of model fit to compare consistency
and inconsistency models, <em>P</em> values from statistical tests, or
summary of inconsistency estimates from different parts of the treatment
network.</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Risk of bias across studies</p>
</blockquote></td>
<td>22</td>
<td>Present results of any assessment of risk of bias across studies for
the evidence base being studied.</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Results of additional analyses</p>
</blockquote></td>
<td>23</td>
<td>Give results of additional analyses, if done (e.g., sensitivity or
subgroup analyses, meta-regression analyses<em>, alternative network
geometries studied, alternative choice of prior distributions for
Bayesian analyses,</em> and so forth).</td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td><strong>DISCUSSION</strong></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Summary of evidence</p>
</blockquote></td>
<td>24</td>
<td>Summarize the main findings, including the strength of evidence for
each main outcome; consider their relevance to key groups (e.g.,
healthcare providers, users, and policy-makers).</td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Limitations</p>
</blockquote></td>
<td>25</td>
<td>Discuss limitations at study and outcome level (e.g., risk of bias),
and at review level (e.g., incomplete retrieval of identified research,
reporting bias). <em>Comment on the validity of the assumptions, such as
transitivity and consistency. Comment on any concerns regarding network
geometry (e.g., avoidance of certain comparisons).</em></td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Conclusions</p>
</blockquote></td>
<td>26</td>
<td>Provide a general interpretation of the results in the context of
other evidence, and implications for future research.</td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td><strong>FUNDING</strong></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td><blockquote>
<p>Funding</p>
</blockquote></td>
<td>27</td>
<td>Describe sources of funding for the systematic review and other
support (e.g., supply of data); role of funders for the systematic
review. This should also include information regarding whether funding
has been received from manufacturers of treatments in the network and/or
whether some of the authors are content experts with professional
conflicts of interest that could affect use of treatments in the
network.</td>
<td></td>
</tr>
</tbody>
</table>

PICOS = population, intervention, comparators, outcomes, study design.

\* Text in italics indicates wording specific to reporting of network
meta-analyses that has been added to guidance from the PRISMA statement.

† Authors may wish to plan for use of appendices to present all relevant
information in full detail for items in this section.


</details>

In [109]:
!pandoc -f docx -t markdown-pipe_tables "PRISMA NMA checklist.docx" -o prisma-nma.md

In [ ]:
gitignore = f"""*.gsheet
*/*.gsheet"""

with open("./.gitignor


Define directory structure and store paths as global variables.

```
./research/
├── ./research/systematic_review/
|   |   
│   ├── ./research/systematic_review/protocol/  
|   |   |
│   │   ├── ./research/systematic_review/protocol/prospero  
│   │   └── ./research/systematic_review/protocol/cochrane  
|   |
│   ├── ./research/systematic_review/search_strategy/  
|   |   |
│   │   ├── ./research/systematic_review/search_strategy/pubmed  
│   │   ├── ./research/systematic_review/search_strategy/embase  
│   │   └── ./research/systematic_review/search_strategy/wos  
|   |
│   ├── ./research/systematic_review/search/  
|   |   |
│   │   ├── ./research/systematic_review/search/pubmed
│   │   ├── ./research/systematic_review/search/embase
│   │   └── ./research/systematic_review/search/wos
|   |
│   ├── ./research/systematic_review/deduplication/
|   |   |
│   │   ├── ./research/systematic_review/deduplication/doi
│   │   ├── ./research/systematic_review/deduplication/key
│   │   └── ./research/systematic_review/deduplication/id
|   |
│   └── ./research/systematic_review/screening/
|       |
│       ├── ./research/systematic_review/screening/title_abstract_screening
│       ├── ./research/systematic_review/screening/PDF
│       └── ./research/systematic_review/screening/full-text_screening
|
├── ./research/data
├── ./research/meta-analysis
├── ./research/manuscript
├── ./research/README.ipynb
├── ./research/docs
└── ./research/src
```

In [ ]:
!python.exe -m venv .venv
!python.exe -m pip install --upgrade pip
!pip install -r requirements.txt

In [88]:
import subprocess
import sys
import os
import pandas as pd
from Bio import Entrez, Medline
import ssl
import certifi
import re
from pathlib import Path

In [99]:
# Set absolute directory paths for important sub-project folders as variables in the global environment for use in scripts downstream and make them in order to start the project.

root = os.getcwd()
folders = {
    "systematic_review": f"{root}/systematic_review",
    "protocol": f"{root}/systematic_review/protocol",
    "search_strategy": f"{root}/systematic_review/search_strategy",
    "search": f"{root}/systematic_review/search",
    "deduplication": f"{root}/systematic_review/deduplication",
    "screening": f"{root}/systematic_review/screening",
    "title_abstract": f"{root}/systematic_review/screening/title_abstract_screening", 
    "pdf": f"{root}/systematic_review/screening/PDF",
    "full_text": f"{root}/systematic_review/screening/full_text_screening" 
}

for var, f in folders.items():
    directory = Path(f)
    globals()[f"{var}"] = directory
    os.makedirs(directory, exist_ok = True)

[top](#toc) | [next](#search)  
[search strategy](#search-strategy) | [search](#search) | [deduplication](#deduplication) | [screening](#screening)

<a id="search-strategy"></a>

<div align="center">
	<font size="5" style="font-family:Times New Roman;font-variant: small-caps;">Search Strategy</font><br>
</div>

---

<a Section_id="here"></a>

**Create search strategies** for randomized controlled trials: `pm_bptb.txt`, `pm_ht.txt`, `pm_qt.txt`, `pm_plt.txt`, `pm_at.txt` and `pm_ta.txt` corresponding to PubMed search strategies for patellar, hamstring, quadriceps, peroneus longus, achilles and tibialis anterior and posterior tendones, respectively. From the protocol that was developed, extract key terms from the eligibility criteria for inclusion and exclusion of studies in order to develop a *search strategy*.

In [49]:
acl = f"""("anterior cruciate ligament"[mh] OR "anterior cruciate ligament reconstruction"[tiab])"""
rct = f"""("randomized controlled trial"[pt])"""
reviews = f"""("review"[pt] OR "systematic review"[pt] OR "meta-analysis"[pt]"""
outcomes = f"""(("ikdc"[tiab] OR "lysholm"[tiab] OR "tegner"[tiab] OR (("instrumental laxity"[tiab] OR "kt-1000"[tiab] OR "kt-2000"[tiab] OR "rolimeter"[tiab]) OR "pivot shift"[tiab] OR "lachman"[tiab]) OR ("graft failure"[tiab] OR "graft rupture"[tiab]))"""

bptb = f"""("bone-patellar tendon-bone"[tiab] OR "patellar tendon"[tiab] OR "bptb"[tiab])"""
ht = f"""("hamstring tendon"[tiab] OR "semitendinosus"[tiab] OR "gracilis"[tiab])"""
qt = f"""("quadriceps"[tiab] OR "qt"[tiab])"""
plt = f"""("peroneus longus"[tiab] OR "fibularis longus"[tiab])"""
at = f"""("achilles"[tiab])"""
ta = f"""("tibialis anterior"[tiab] OR "tibialis posterior"[tiab])"""

In [50]:
subgroups = {"bptb": bptb, 
             "ht": ht, 
             "qt": qt, 
             "plt": plt, 
             "at": at, 
             "ta": ta}

queries = {}

# Create pm_bptb, etc.
for x, y in subgroups.items():
    globals()[f"pm_{x}"] = f"{acl} AND {rct} AND {y}"
    with open(f"{search_strategy}/pubmed/pm_{x}.txt", 'w') as f:
        f.write(f"{acl} AND {rct} AND {y}")
    with open(f"{search_strategy}/pubmed/reviews_pm_{x}.txt", 'w') as f:
        f.write(f"{acl} AND {reviews} AND {y}")


# The search strategies were 'translated' via regular expressions from PubMed syntax to Embase and Web of Science syntax.

pm_queries = {
    "bptb": pm_bptb,
    "ht": pm_ht,
    "qt": pm_qt,
    "plt": pm_plt,
    "at": pm_at,
    "ta": pm_ta
}

# translate into embase queries from pubmed queries using regex and store them into the global environment.


# Create em_bptb, etc.
for x, y in pm_queries.items():
    query = re.sub(r"\[(.*?)\]",":\\1", y)
    query = re.sub(r"\:tiab",":ti,ab", query)
    query = re.sub(r"\:mh","/exp", query)
    query = re.sub(r"\:pt",":it,ti,ab", query)
    query = re.sub(r'"',"'", query)
    globals()[f"em_{x}"] = query
    with open(f"{search_strategy}/embase/em_{x}.txt", 'w') as f:
        f.write(query)

# Create wos_bptb, etc.
for x, y in pm_queries.items():
    query = re.sub(r'"(.*?)"\[(.*?)\]','\\2="\\1"', y)
    query = re.sub(r'tiab="(.*?)"','(TI=(\\1) OR AB=(\\1))', query)
    query = re.sub(r'mh="(.*?)"','(TMIC=(\\1))', query)
    query = re.sub(r'pt="(.*?)"','(TS=(\\1))', query)
    globals()[f"wos_{x}"] = query

    with open(f"{search_strategy}/wos/wos_{x}.txt", 'w') as f:
        f.write(query)

---

[previous](#search-strategy) | [top](#toc) | [next](#deduplication)  
[search strategy](#search-strategy) | [search](#search) | [deduplication](#deduplication) | [screening](#screening)

<a id="search"></a>
<div align="center">
	<font size="5" style="font-family:Times New Roman;font-variant: small-caps;">Search</font><br>
</div>

---

A script to either create a search strategy using the terms, field tags, and Boolean operators and save them as plain text files or load already written and saved plain text files for import into the API search scripts. This uses the search strategies (e.g., `pm_bptb.txt`, search strategy in plain text written in PubMed syntax for bone-patellar tendon-bone (BPTB) subgroup search) and pulls data from PubMed to output PMIDs (`pmid_pm_bptb.txt`) and search results in XML (`pm_bptb.xml`) and parses this into CSV files (`pm_bptb.csv`).

In [29]:
ssl._create_default_https_context = lambda: ssl.create_default_context(
    cafile=certifi.where()
)
# create search strategy using structured inputs

question = input("Do you already have a search strategy file saved?")
filename = input("Enter the file name of the search strategy: ")
file = f"{search_strategy}/pubmed/{filename}.txt"

if question == "no":
    parts = []
    string = []
    while True:
        term = input("Enter the search string: ")
        field = input("Enter the field type: ")
        string.append(f"'{term}'[{field}]")
        boolean = input("Enter the Boolean operator (e.g., OR, AND, NOT): ")
        
        if boolean == "OR":
            continue
    
        parts.append("(" + " OR ".join(string) + ")")
        string = []
    
        if boolean == "":
            break
            
        parts.append(boolean)
        
    query = " ".join(parts) # query = search strategy FROM HERE
    with open(file, "w") as f:
        f.write(query)
    
with open(file, "r") as f:
    query = f.read()

query = f"{query}"

# use NCBI's e-utitilies to pull PMIDs using e-search.

Entrez.email = "dkim246@jhmi.edu"
Entrez.api_key = 'bb1c481d8e167acd16f3616593c18b3aab08'

handle = Entrez.esearch(db= "pubmed", 
                        term = query, 
                        usehistory = "y", 
                        retmax = 1000,
                        retmode = "xml")

pmid = Entrez.read(handle)

pmid = pmid['IdList']
pmid = ",".join(pmid) # list to string
#with open(f"./data/pmid_{filename}.txt", 'w') as f:
#    f.write(pmid)
with open(f"{search}/pubmed/pmid_{filename}.txt", 'w') as f:
    f.write(pmid)
handle.close()

# ncbi e-summary
handle = Entrez.esummary(db= "pubmed", 
                         id = pmid, 
                         retmode = "xml", 
                         usehistory = "y", 
                         retmax = 1000)

xml = handle.read()
#xml_file = f"./data/{filename}.xml"
xml_file = f"{search}/pubmed/{filename}.xml"
with open(xml_file, "wb") as f:
    f.write(xml)   
handle.close()

import xml.etree.ElementTree as ET

tree = ET.parse(f"{xml_file}")
root = tree.getroot()

docsum = root[0]

def xml_parse(docsum):
    df = {}
    df["pmid"] = docsum.find("Id").text
    for item in docsum.findall("Item"):
        key = item.attrib.get("Name")
        if item.attrib.get("Type") == "List":
            values = [sub.text for sub in item.findall("Item") if sub.text]
            df[key] = values
        else:
            df[key] = item.text
    return df
records = [xml_parse(doc) for doc in root.findall(".//DocSum")]
df = pd.DataFrame(records)

csv_file = f"{search}/pubmed/{filename}.csv"
df.to_csv(csv_file, encoding = "utf-8")

# using e-fetch, the abstracts are pulled

handle = Entrez.efetch(
    db="pubmed",
    id=pmid,
    rettype="medline",
    retmode="text"
)

text = list(Medline.parse(handle))
print(text)
handle.close()

abstracts = pd.DataFrame(text)[["PMID", "AB"]]
abstracts.rename(columns = {"PMID":"pmid", "AB":"abstract"}, inplace = True)
df = df.merge(abstracts, on = "pmid", how = "left")
df['year'] = df['PubDate'].str[:4]
globals()[f"{filename}"] = df
csv_file = f"{search}/pubmed/{filename}.csv"
df.to_csv(csv_file, encoding = "utf-8")
num = len(df)
print(f"Number of records found: {num}")

Do you already have a search strategy file saved? yes
Enter the file name of the search strategy:  pm_ta

[{'PMID': '35114581', 'OWN': 'NLM', 'STAT': 'MEDLINE', 'DCOM': '20220318', 'LR': '20230302', 'IS': '1873-2380 (Electronic) 0021-9290 (Print) 0021-9290 (Linking)', 'VI': '133', 'DP': '2022 Mar', 'TI': 'Wavelet analysis reveals differential lower limb muscle activity patterns long after anterior cruciate ligament reconstruction.', 'PG': '110957', 'LID': 'S0021-9290(22)00016-1 [pii] 10.1016/j.jbiomech.2022.110957 [doi]', 'AB': 'The purpose of this study was to test whether differences in muscle activity patterns between anterior cruciate ligament-reconstructed patients (ACLR) and healthy controls could be detected 10 to 15 years post-surgery using a machine learning classification approach. Eleven ACLR subjects and 12 healthy controls were recruited from an ongoing prospective randomized clinical trial. Surface electromyography (EMG) signals were recorded from gastrocnemius medialis and lateralis, tibialis anterior, vastus medialis, rectus femoris, biceps femoris, and semitendinosus muscles. Muscle activity was analyzed using wavelet analysis and examined within four sub-phases of the hop test, as well as an average of the task as a whole. K-nearest neighbor machine learning combined with a leave-one-out validation was used to classify the muscle activity patterns as either ACLR or Control. When muscle activity was averaged across the whole hop task, activity patterns for all muscles except the tibialis anterior were identified as being different between the study cohorts. ACLR patients demonstrated continuous muscle activities that spanned take-off, airborne, and landing hop phases versus healthy controls who displayed timed and regulated islets of muscle activities specific to each hop phase. The most striking features were 25-50% greater relative quadriceps intensity and approximately 66% diminished biceps femoris intensity in ACLR patients. The current findings are in contrast to previous work using conventional co-contraction and muscle activation onset EMG measures of the same dataset, underscoring the sensitivity and potential of the wavelet approach coupled with machine learning to reveal meaningful adaptation strategies in this at-risk population.', 'CI': ['Copyright (c) 2022 Elsevier Ltd. All rights reserved.'], 'FAU': ['Zandiyeh, Payam', 'Parola, Lauren R', 'Fleming, Braden C', 'Beveridge, Jillian E'], 'AU': ['Zandiyeh P', 'Parola LR', 'Fleming BC', 'Beveridge JE'], 'AD': ['Department of Orthopaedic Surgery, University of Texas Health Sciences Center at Houston, TX, USA. Electronic address: payam.zandiyeh@uth.tmc.edu.', 'Department of Orthopaedics, Warren Alpert Medical School of Brown University/Rhode Island Hospital, Providence, RI, USA. Electronic address: lauren_parola@brown.edu.', 'Department of Orthopaedics, Warren Alpert Medical School of Brown University/Rhode Island Hospital, Providence, RI, USA. Electronic address: braden_fleming@brown.edu.', 'Department of Orthopaedics, Warren Alpert Medical School of Brown University/Rhode Island Hospital, Providence, RI, USA; Cleveland Clinic Biomedical Engineering Department, Cleveland, OH, USA. Electronic address: beverij2@ccf.org.'], 'LA': ['eng'], 'GR': ['R01 AR047910/AR/NIAMS NIH HHS/United States', 'R01 AR074973/AR/NIAMS NIH HHS/United States', 'P30 GM122732/GM/NIGMS NIH HHS/United States', 'K99 AR069094/AR/NIAMS NIH HHS/United States', 'R00 AR069094/AR/NIAMS NIH HHS/United States'], 'PT': ['Journal Article', 'Randomized Controlled Trial', 'Research Support, N.I.H., Extramural', "Research Support, Non-U.S. Gov't"], 'DEP': '20220120', 'PL': 'United States', 'TA': 'J Biomech', 'JT': 'Journal of biomechanics', 'JID': '0157375', 'SB': 'IM', 'MH': ['*Anterior Cruciate Ligament Injuries/surgery', '*Anterior Cruciate Ligament Reconstruction', '*Hamstring Muscles', 'Humans', 'Lower Extremity/surgery', 'Muscle, Skeletal/physiology', 'Prospective Studies', 'Quadriceps Muscle/surgery', 'Wavelet Analysis'], 'PMC': 'PMC8893161', 'MID': ['NIHMS1775927'], 'OTO': ['NOTNLM'], 'OT': ['Anterior cruciate ligament reconstruction', 'Electromyography, wavelet analysis', 'K-nearest neighbor', 'Neuromuscular function'], 'COIS': ['CONFLICT OF INTEREST Dr. Fleming receives royalties from Springer Publishing and', 'a stipend from Sage Publishing as an associate editor for a medical journal and', 'is a Miach Orthopaedics LLC founder. All other authors do not have any conflicts', "of interest that may have influenced this study's results. Results of the present", 'study are presented honestly and without fabrication, falsification, or', 'inappropriate data manipulation.'], 'EDAT': '2022/02/04 06:00', 'MHDA': '2022/03/19 06:00', 'PMCR': ['2023/03/01'], 'CRDT': ['2022/02/03 20:17'], 'PHST': ['2021/06/22 00:00 [received]', '2022/01/05 00:00 [revised]', '2022/01/06 00:00 [accepted]', '2022/02/04 06:00 [pubmed]', '2022/03/19 06:00 [medline]', '2022/02/03 20:17 [entrez]', '2023/03/01 00:00 [pmc-release]'], 'AID': ['S0021-9290(22)00016-1 [pii]', '10.1016/j.jbiomech.2022.110957 [doi]'], 'PST': 'ppublish', 'SO': 'J Biomech. 2022 Mar;133:110957. doi: 10.1016/j.jbiomech.2022.110957. Epub 2022 Jan 20.'}, {'PMID': '31828089', 'OWN': 'NLM', 'STAT': 'MEDLINE', 'DCOM': '20200423', 'LR': '20220411', 'IS': '2314-6141 (Electronic) 2314-6133 (Print)', 'VI': '2019', 'DP': '2019', 'TI': 'Effects on Lower Extremity Neuromuscular Control Exercises on Knee Proprioception, Muscle Strength, and Functional Level in Patients with ACL Reconstruction.', 'PG': '1694695', 'LID': '10.1155/2019/1694695 [doi] 1694695', 'AB': 'OBJECTIVE: The purpose of this study was to determine the effects of lower extremity motor control exercises on knee proprioception, muscle strength, and functional level in patients with anterior cruciate ligament reconstruction (ACL-R). MATERIALS AND METHODS: Thirty-two of the 57 patients with ACL-R using tibialis anterior allografts were divided into two groups. Group I: lower extremity motor control exercises were added to the standard rehabilitation program. Group II: standard rehabilitation program was applied. Effects of lower extremity motor control exercises on quadriceps and hamstring muscles strength, knee joint position sense, and hop test were evaluated. RESULTS: There were no differences in muscle strength and endurance of the quadriceps and hamstring between the operative and nonoperative sides in Group I (p > 0.05) while there were significant differences in strength of the quadriceps and hamstring between the operative and nonoperative sides in Group II (p < 0.05). There were significant differences in the endurance of the quadriceps and hamstring and knee joint position sense at 15 degrees , 45 degrees , and 75 degrees  between the operative sides of the patients in both groups (p < 0.05). CONCLUSIONS: The neuromuscular control exercises program was found to be more effective in reducing the difference in strength while the standard program was found to be more effective in reducing the difference in endurance between the operated knee and the other knee. This study revealed that neuromuscular control exercises should also be used to improve knee proprioception sense following ACL-R.', 'CI': ['Copyright (c) 2019 Defne Kaya et al.'], 'FAU': ['Kaya, Defne', 'Guney-Deniz, Hande', 'Sayaca, Cetin', 'Calik, Mahmut', 'Doral, Mahmut Nedim'], 'AU': ['Kaya D', 'Guney-Deniz H', 'Sayaca C', 'Calik M', 'Doral MN'], 'AUID': ['ORCID: 0000-0003-0552-1190'], 'AD': ['Department of Physical Therapy and Rehabilitation, Faculty of Health Sciences, Uskudar University, Istanbul, Turkey.', 'Department of Physical Therapy and Rehabilitation, Faculty of Health Sciences, Istinye University, Istanbul, Turkey.', 'Department of Physical Therapy and Rehabilitation, Faculty of Health Sciences, Istanbul Okan University, Istanbul, Turkey.', 'Department of Physical Therapy and Rehabilitation, Faculty of Health Sciences, Hacettepe University, Ankara, Turkey.', 'Department of Physical Therapy and Rehabilitation, Faculty of Health Sciences, Uskudar University, Istanbul, Turkey.', 'Department of Physical Therapy and Rehabilitation, Faculty of Health Sciences, Uskudar University, Istanbul, Turkey.', 'Department of Orthopaedics & Traumatology, Faculty of Medicine, Ufuk University, Ankara, Turkey.'], 'LA': ['eng'], 'PT': ['Journal Article', 'Randomized Controlled Trial'], 'DEP': '20191115', 'PL': 'United States', 'TA': 'Biomed Res Int', 'JT': 'BioMed research international', 'JID': '101600173', 'SB': 'IM', 'MH': ['Adolescent', 'Adult', 'Anterior Cruciate Ligament/*physiopathology', 'Anterior Cruciate Ligament Injuries/*physiopathology', 'Anterior Cruciate Ligament Reconstruction/rehabilitation', 'Exercise/*physiology', 'Exercise Therapy/methods', 'Female', 'Humans', 'Joint Instability/physiopathology', 'Knee Injuries/*physiopathology', 'Knee Joint/physiopathology', 'Lower Extremity/*physiopathology', 'Male', 'Middle Aged', 'Muscle Strength/*physiology', 'Muscle, Skeletal/physiopathology', 'Proprioception/physiology', 'Range of Motion, Articular/physiology', 'Young Adult'], 'PMC': 'PMC6881759', 'COIS': ['All authors have no conflicts of interest with respect to the data collected and', 'procedures used within this study.'], 'EDAT': '2019/12/13 06:00', 'MHDA': '2020/04/24 06:00', 'PMCR': ['2019/11/15'], 'CRDT': ['2019/12/13 06:00'], 'PHST': ['2019/10/01 00:00 [received]', '2019/10/31 00:00 [accepted]', '2019/12/13 06:00 [entrez]', '2019/12/13 06:00 [pubmed]', '2020/04/24 06:00 [medline]', '2019/11/15 00:00 [pmc-release]'], 'AID': ['10.1155/2019/1694695 [doi]'], 'PST': 'epublish', 'SO': 'Biomed Res Int. 2019 Nov 15;2019:1694695. doi: 10.1155/2019/1694695. eCollection 2019.'}, {'PMID': '27876265', 'OWN': 'NLM', 'STAT': 'MEDLINE', 'DCOM': '20170815', 'LR': '20170815', 'IS': '1873-5800 (Electronic) 0968-0160 (Linking)', 'VI': '23', 'IP': '6', 'DP': '2016 Dec', 'TI': 'A prospective randomized comparison of two distinct allogenic tissue constructs for anterior cruciate ligament reconstruction.', 'PG': '1112-1120', 'LID': 'S0968-0160(16)30144-2 [pii] 10.1016/j.knee.2016.08.011 [doi]', 'AB': 'BACKGROUND: Conduct a prospective randomized study to compare clinical outcomes of anterior cruciate ligament (ACL) reconstruction using quadrupled hamstring tendon (HT) allograft or doubled tibialis anterior (TA) allograft. Limited level 1 data exist comparing outcomes of different soft tissue allograft constructs for ACL reconstruction. We hypothesized no difference would exist in the patient reported outcomes (PRO), arthrometric testing, or rate of re-rupture between the two constructs. METHODS: Ninety eight subjects undergoing primary ACL reconstruction were randomized to HT (n=47) or TA (n=51) allograft. Subjects completed validated (PRO) measures pre-operatively, and six months and two years post-operatively. Arthrometric testing was performed at six months to assess integrity of the reconstruction. RESULTS: Fifty-eight percent of subjects (57/98) completed a two-year follow up. Allograft re-tear rates were similar between groups (6.2% HT vs. 4.0% TA, respectively, p=1.0). The relative risk of re-tear in the HT group was 1.5 compared to the TA group (p=0.7). The TA group improved significantly more on the physical portion of the VR-12 (p=0.046) and Lysholm score (p=0.014) compared to the HT group. There was no difference in the change from baseline for the other PRO scores at two years. CONCLUSIONS: Our data indicate no difference in graft failure rate and similar improvement from baseline in most PRO scores between treatment groups after two years. Based on these findings, TA allograft appears to provide a reliable and satisfactory option for patients who elect to undergo allograft ACL reconstruction.', 'CI': ['Copyright A(c) 2016. Published by Elsevier B.V.'], 'FAU': ['Rose, Michael B', 'Domes, Christopher', 'Farooqi, Mehwish', 'Crawford, Dennis C'], 'AU': ['Rose MB', 'Domes C', 'Farooqi M', 'Crawford DC'], 'AD': ['Department of Orthopedic Surgery and Rehabilitation, Oregon Health and Science University, 3181 S.W. Sam Jackson Park Road, Portland, OR 97239-3098, United States.', 'Department of Orthopedic Surgery and Rehabilitation, Oregon Health and Science University, 3181 S.W. Sam Jackson Park Road, Portland, OR 97239-3098, United States.', 'Department of Orthopedic Surgery and Rehabilitation, Oregon Health and Science University, 3181 S.W. Sam Jackson Park Road, Portland, OR 97239-3098, United States.', 'Department of Orthopedic Surgery and Rehabilitation, Oregon Health and Science University, 3181 S.W. Sam Jackson Park Road, Portland, OR 97239-3098, United States. Electronic address: crawfden@ohsu.edu.'], 'LA': ['eng'], 'PT': ['Comparative Study', 'Journal Article', 'Randomized Controlled Trial'], 'DEP': '20161118', 'PL': 'Netherlands', 'TA': 'Knee', 'JT': 'The Knee', 'JID': '9430798', 'SB': 'IM', 'MH': ['Adult', 'Anterior Cruciate Ligament Injuries/*surgery', 'Anterior Cruciate Ligament Reconstruction/*methods', 'Arthrometry, Articular', 'Female', 'Humans', 'Knee Joint', 'Male', 'Prospective Studies', 'Range of Motion, Articular', 'Recovery of Function', 'Tendons/*transplantation', 'Treatment Outcome'], 'OTO': ['NOTNLM'], 'OT': ['ACL reconstruction', 'Allograft', 'Hamstring tendon', 'Semitendinosis', 'Tibialis anterior'], 'EDAT': '2016/11/24 06:00', 'MHDA': '2017/08/16 06:00', 'CRDT': ['2016/11/24 06:00'], 'PHST': ['2016/04/26 00:00 [received]', '2016/08/24 00:00 [revised]', '2016/08/27 00:00 [accepted]', '2016/11/24 06:00 [pubmed]', '2017/08/16 06:00 [medline]', '2016/11/24 06:00 [entrez]'], 'AID': ['S0968-0160(16)30144-2 [pii]', '10.1016/j.knee.2016.08.011 [doi]'], 'PST': 'ppublish', 'SO': 'Knee. 2016 Dec;23(6):1112-1120. doi: 10.1016/j.knee.2016.08.011. Epub 2016 Nov 18.'}, {'PMID': '27570169', 'OWN': 'NLM', 'STAT': 'MEDLINE', 'DCOM': '20171024', 'LR': '20181202', 'IS': '1526-3231 (Electronic) 0749-8063 (Linking)', 'VI': '33', 'IP': '1', 'DP': '2017 Jan', 'TI': 'Braking Reaction Time After Right-Knee Anterior Cruciate Ligament Reconstruction: A Comparison of 3 Grafts.', 'PG': '173-180', 'LID': 'S0749-8063(16)30367-X [pii] 10.1016/j.arthro.2016.05.043 [doi]', 'AB': 'PURPOSE: To determine when patients recover the ability to safely operate the brakes of an automobile after a right-knee anterior cruciate ligament reconstruction (ACLR). METHODS: A computerized driving simulator was used to determine braking ability after an isolated right-knee ACLR. Thirty healthy volunteers were tested at 1 visit to determine normal mean values, and 27 treatment subjects were tested at 1 week, 3 weeks, and 6 weeks after ACLR. Nine study subjects were treated with a patella tendon (BPTB) autograft, 9 were treated with a hamstring (HS) autograft, and 9 were treated with a tibialis anterior (TA) allograft. The driving simulator collected data on brake reaction time (BRT), brake travel time (BTT), and total brake time (TBT) at each visit. RESULTS: The control group generated a BRT of 725 milliseconds, BTT of 2.87 seconds, and TBT of 3.59 seconds. At week 1, all treatment patients had significant differences compared with controls for BRT, BTT, and TBT, except the BTT of the HS group. At week 3, all measures for the allograft group and the BRT for both autograft groups were no longer significantly different compared with controls, but significant differences were found for TBT in the HS and BPTB groups (P = .03, P = .01). At week 6, BRT, BTT, and TBT were no longer significantly different for either the HS group or BPTB group. CONCLUSIONS: Patients who underwent a right-knee ACLR with a TA allograft regained normal braking times by week 3 postoperatively. In contrast, those treated with a BPTB or HS autograft demonstrated significantly delayed braking times at 3 weeks but returned to normal braking ability by week 6. Those treated with an autograft had an earlier return of normalized BRT than BTT. LEVEL OF EVIDENCE: Level III, case-control series.', 'CI': ['Copyright (c) 2016 Arthroscopy Association of North America. Published by Elsevier', 'Inc. All rights reserved.'], 'FAU': ['Wasserman, Bradley R', 'Singh, Brian C', 'Kaplan, Daniel J', 'Weinberg, Maxwell', 'Meislin, Robert', 'Jazrawi, Laith M', 'Strauss, Eric J'], 'AU': ['Wasserman BR', 'Singh BC', 'Kaplan DJ', 'Weinberg M', 'Meislin R', 'Jazrawi LM', 'Strauss EJ'], 'AD': ['NYU Hospital for Joint Disease, New York, New York, U.S.A.', 'NYU Hospital for Joint Disease, New York, New York, U.S.A.', 'NYU Hospital for Joint Disease, New York, New York, U.S.A.. Electronic address: danieljameskaplan@gmail.com.', 'NYU Hospital for Joint Disease, New York, New York, U.S.A.', 'NYU Hospital for Joint Disease, New York, New York, U.S.A.', 'NYU Hospital for Joint Disease, New York, New York, U.S.A.', 'NYU Hospital for Joint Disease, New York, New York, U.S.A.'], 'LA': ['eng'], 'PT': ['Journal Article', 'Randomized Controlled Trial'], 'DEP': '20160825', 'PL': 'United States', 'TA': 'Arthroscopy', 'JT': 'Arthroscopy : the journal of arthroscopic & related surgery : official publication of the Arthroscopy Association of North America and the International Arthroscopy Association', 'JID': '8506498', 'SB': 'IM', 'MH': ['Adolescent', 'Adult', 'Anterior Cruciate Ligament/physiopathology/*surgery', 'Anterior Cruciate Ligament Injuries/physiopathology/surgery', 'Anterior Cruciate Ligament Reconstruction', '*Automobile Driving', 'Case-Control Studies', 'Female', 'Humans', 'Male', 'Postoperative Period', 'Range of Motion, Articular', 'Reaction Time', 'Tendons/*transplantation', 'Transplantation, Autologous', 'Young Adult'], 'EDAT': '2016/08/30 06:00', 'MHDA': '2017/10/25 06:00', 'CRDT': ['2016/08/30 06:00'], 'PHST': ['2015/12/03 00:00 [received]', '2016/05/27 00:00 [revised]', '2016/05/31 00:00 [accepted]', '2016/08/30 06:00 [pubmed]', '2017/10/25 06:00 [medline]', '2016/08/30 06:00 [entrez]'], 'AID': ['S0749-8063(16)30367-X [pii]', '10.1016/j.arthro.2016.05.043 [doi]'], 'PST': 'ppublish', 'SO': 'Arthroscopy. 2017 Jan;33(1):173-180. doi: 10.1016/j.arthro.2016.05.043. Epub 2016 Aug 25.'}, {'PMID': '26311445', 'OWN': 'NLM', 'STAT': 'MEDLINE', 'DCOM': '20160503', 'LR': '20220330', 'IS': '1552-3365 (Electronic) 0363-5465 (Linking)', 'VI': '43', 'IP': '10', 'DP': '2015 Oct', 'TI': 'Autograft Versus Allograft Anterior Cruciate Ligament Reconstruction: A Prospective, Randomized Clinical Study With a Minimum 10-Year Follow-up.', 'PG': '2501-9', 'LID': '10.1177/0363546515596406 [doi]', 'AB': 'BACKGROUND: The use of allografts for anterior cruciate ligament (ACL) reconstruction in young athletes is controversial. No long-term results have been published comparing tibialis posterior allografts to hamstring autografts. PURPOSE: To evaluate the long-term results of primary ACL reconstruction using either an allograft or autograft. STUDY DESIGN: Randomized controlled trial; Level of evidence, 1. METHODS: From June 2002 to August 2003, patients with a symptomatic ACL-deficient knee were randomized to receive either a hamstring autograft or tibialis posterior allograft. All allografts were from a single tissue bank, aseptically processed, and fresh-frozen without terminal irradiation. Graft fixation was identical in all knees. All patients followed the same postoperative rehabilitation protocol, which was blinded to the therapists. Preoperative and postoperative assessments were performed via examination and/or telephone and Internet-based questionnaire to ascertain the functional and subjective status using established knee metrics. The primary outcome measures were graft integrity, subjective knee stability, and functional status. RESULTS: There were 99 patients (100 knees); 86 were men, and 95% were active-duty military. Both groups were similar in demographics and preoperative activity level. The mean and median ages of both groups were identical at 29 and 26 years, respectively. Concomitant meniscal and chondral pathologic abnormalities, microfracture, and meniscal repair performed at the time of reconstruction were similar in both g

In [20]:
print(pm_bptb)

         pmid       PubDate     EPubDate                               Source  \
0    40308075      2025 May   2025 May 1                      Am J Sports Med
1    39194385      2025 Apr  2024 Aug 28  Knee Surg Sports Traumatol Arthrosc
2    38226736      2024 Feb   2024 Jan 7  Knee Surg Sports Traumatol Arthrosc
3    37893482    2023 Oct 3   2023 Oct 3                    Medicina (Kaunas)
4    35762124      2023 May  2022 Jun 27                        Sports Health
..        ...           ...          ...                                  ...
185   8403647      1993 Oct          NaN                Clin Orthop Relat Res
186   1558237  1992 Mar-Apr          NaN                      Am J Sports Med
187   2009118          1991          NaN                          Arthroscopy
188   2285086  1990 Nov-Dec          NaN                      Am J Sports Med
189   2323135      1990 May          NaN                Clin Orthop Relat Res

                                            AuthorList      LastAuthor  \
0    [Rao N, Triana J, Avila A, Campbell KA, Alaia ...      Strauss EJ
1    [Martorell-de Fortuny L, Torres-Claramunt R, S...      Monllau JC
2    [Martin RK, Marmura H, Wastvedt S, Pareek A, P...       Getgood A
3    [Obradović M, Ninković S, Gvozdenović N, Tošić...         Dulić O
4    [Jack RA 2nd, Lambert BS, Hedt CA, Delgado D, ...    McCulloch PC
..                                                 ...             ...
185               [Engström B, Wredmark T, Westblad P]      Westblad P
186                  [Rosen MA, Jackson DW, Atwell EA]       Atwell EA
187         [Richmond JC, Gladstone J, MacGillivray J]  MacGillivray J
188  [Engebretsen L, Benum P, Fasting O, Mølster A,...        Strand T
189                                           [Kohn D]          Kohn D

                                                 Title Volume Issue  \
0    Postoperative Pain and Opioid Usage With Combi...     53     6
1    Patellar bone defect grafting does not reduce ...     33     4
2    External validation of the Norwegian anterior ...     32     2
3    Tubularization of Bone-Tendon-Bone Grafts: Eff...     59    10
4    Blood Flow Restriction Therapy Preserves Lower...     15     3
..                                                 ...    ...   ...
185  Patellar tendon or Leeds-Keio graft in the sur...    NaN   295
186  The efficacy of continuous passive motion in t...     20     2
187  Continuous passive motion after arthroscopical...      7     1
188  A prospective, randomized study of three surgi...     18     6
189  Arthroscopic evaluation of anterior cruciate l...    NaN   254

         Pages  ...                                         ArticleIds  \
0    1359-1367  ...              [40308075, 10.1177/03635465251328609]
1    1299-1307  ...                      [39194385, 10.1002/ksa.12449]
2      206-213  ...                      [38226736, 10.1002/ksa.12031]
3          NaN  ...  [37893482, PMC10608507, pmc-id: PMC10608507;, ...
4      361-371  ...  [35762124, PMC10170230, pmc-id: PMC10170230;, ...
..         ...  ...                                                ...
185      190-7  ...                                          [8403647]
186      122-7  ...              [1558237, 10.1177/036354659202000205]
187      39-44  ...  [2009118, 10.1016/0749-8063(91)90076-a, 0749-8...
188     585-90  ...              [2285086, 10.1177/036354659001800605]
189      220-4  ...                                          [2323135]

                              DOI  \
0       10.1177/03635465251328609
1               10.1002/ksa.12449
2               10.1002/ksa.12031
3        10.3390/medicina59101764
4       10.1177/19417381221101006
..                            ...
185                           NaN
186    10.1177/036354659202000205
187  10.1016/0749-8063(91)90076-a
188    10.1177/036354659001800605
189                           NaN

                                               History  \
0    [2025/05/01 06:28, 2025/05/01 06:27, 2025/05/0...
1    [2024/08/04 00:00, 2024/05/15 00:00, 2024/08/0...
2    [2023/11/10 00:00, 2023/09/14 00:00, 2023/12/0...
3    [2023/08/31 00:00, 2023/09/24 00:00, 2023/09/2...
4    [2023/04/26 06:41, 2022/06/29 06:00, 2022/06/2...
..                                                 ...
185  [1993/10/01 00:00, 1993/10/01 00:01, 1993/10/0...
186  [1992/03/01 00:00, 1992/03/01 00:01, 1992/03/0...
187  [1991/01/01 00:00, 1991/01/01 00:01, 1991/01/0...
188  [1990/11/01 00:00, 1990/11/01 00:01, 1990/11/0...
189  [1990/05/01 00:00, 1990/05/01 00:01, 1990/05/0...

                      References HasAbstract PmcRefCount  \
0                             []           1           0
1                             []           1           0
2                             []           1           0
3                             []           1          48
4                             []           1          58
..                           ...         ...         ...
185                           []           1           0
186                           []           1           0
187  [Arthroscopy 1991;7(2):256]           1           0
188                           []           1           0
189                           []           1           0

                                       FullJournalName  \
0              The American journal of sports medicine
1    Knee surgery, sports traumatology, arthroscopy...
2    Knee surgery, sports traumatology, arthroscopy...
3                         Medicina (Kaunas, Lithuania)
4                                        Sports health
..                                                 ...
185         Clinical orthopaedics and related research
186            The American journal of sports medicine
187  Arthroscopy : the journal of arthroscopic & re...
188            The American journal of sports medicine
189         Clinical orthopaedics and related research

                        ELocationID                         SO  \
0    doi: 10.1177/03635465251328609   2025 May;53(6):1359-1367
1            doi: 10.1002/ksa.12449   2025 Apr;33(4):1299-1307
2            doi: 10.1002/ksa.12031     2024 Feb;32(2):206-213
3     doi: 10.3390/medicina59101764          2023 Oct 3;59(10)
4    doi: 10.1177/19417381221101006     2023 May;15(3):361-371
..                              ...                        ...
185                             NaN       1993 Oct;(295):190-7
186                             NaN   1992 Mar-Apr;20(2):122-7
187                             NaN            1991;7(1):39-44
188                             NaN  1990 Nov-Dec;18(6):585-90
189                             NaN       1990 May;(254):220-4

                                              abstract
0    BACKGROUND: Efforts to decrease pain, improve ...
1    PURPOSE: Donor site morbidity is the main draw...
2    PURPOSE: A machine learning-based anterior cru...
3    Background and Objectives: The study addresses...
4    BACKGROUND: Muscle atrophy is common after an ...
..                                                 ...
185  In a prospective randomized study, 60 patients...
186  Seventy-five patients undergoing arthroscopica...
187  The use of continuous passive motion (CPM) fol...
188  Treatment of ACL tears is controversial. Recen...
189  In a prospective study, follow-up arthroscopy ...

[190 rows x 27 columns]

In [23]:
df = pm_bptb
df.head()

,pmid,PubDate,EPubDate,Source,AuthorList,LastAuthor,Title,Volume,Issue,Pages,...,DOI,History,References,HasAbstract,PmcRefCount,FullJournalName,ELocationID,SO,abstract,year
0,40308075,2025 May,2025 May 1,Am J Sports Med,"[Rao N, Triana J, Avila A, Campbell KA, Alaia ...",Strauss EJ,Postoperative Pain and Opioid Usage With Combi...,53,6,1359-1367,...,10.1177/03635465251328609,"[2025/05/01 06:28, 2025/05/01 06:27, 2025/05/0...",[],1,0,The American journal of sports medicine,doi: 10.1177/03635465251328609,2025 May;53(6):1359-1367,"BACKGROUND: Efforts to decrease pain, improve ...",2025
1,39194385,2025 Apr,2024 Aug 28,Knee Surg Sports Traumatol Arthrosc,"[Martorell-de Fortuny L, Torres-Claramunt R, S...",Monllau JC,Patellar bone defect grafting does not reduce ...,33,4,1299-1307,...,10.1002/ksa.12449,"[2024/08/04 00:00, 2024/05/15 00:00, 2024/08/0...",[],1,0,"Knee surgery, sports traumatology, arthroscopy...",doi: 10.1002/ksa.12449,2025 Apr;33(4):1299-1307,PURPOSE: Donor site morbidity is the main draw...,2025
2,38226736,2024 Feb,2024 Jan 7,Knee Surg Sports Traumatol Arthrosc,"[Martin RK, Marmura H, Wastvedt S, Pareek A, P...",Getgood A,External validation of the Norwegian anterior ...,32,2,206-213,...,10.1002/ksa.12031,"[2023/11/10 00:00, 2023/09/14 00:00, 2023/12/0...",[],1,0,"Knee surgery, sports traumatology, arthroscopy...",doi: 10.1002/ksa.12031,2024 Feb;32(2):206-213,PURPOSE: A machine learning-based anterior cru...,2024
3,37893482,2023 Oct 3,2023 Oct 3,Medicina (Kaunas),"[Obradović M, Ninković S, Gvozdenović N, Tošić...",Dulić O,Tubularization of Bone-Tendon-Bone Grafts: Eff...,59,10,NaN,...,10.3390/medicina59101764,"[2023/08/31 00:00, 2023/09/24 00:00, 2023/09/2...",[],1,48,"Medicina (Kaunas, Lithuania)",doi: 10.3390/medicina59101764,2023 Oct 3;59(10),Background and Objectives: The study addresses...,2023
4,35762124,2023 May,2022 Jun 27,Sports Health,"[Jack RA 2nd, Lambert BS, Hedt CA, Delgado D, ...",McCulloch PC,Blood Flow Restriction Therapy Preserves Lower...,15,3,361-371,...,10.1177/19417381221101006,"[2023/04/26 06:41, 2022/06/29 06:00, 2022/06/2...",[],1,58,Sports health,doi: 10.1177/19417381221101006,2023 May;15(3):361-371,BACKGROUND: Muscle atrophy is common after an ...,2023

The CSV files from the three databases were now cleaned, prepared, and transformed; this is otherwise known as 'data wrangling' in Data Science.

In [41]:
# import the exported csv files into the global environment
# convert Web of Science exports to csv

import pandas as pd

subgroups = {
    "bptb": "patellar",
    "ht": "hamstring",
    "qt": "quadriceps",
    "plt": "peroneus",
    "at": "achilles",
    "ta": "tibialis"}

for x, y in subgroups.items():
    df = pd.read_csv(f"{search}/wos/tsv/wos_{x}.tsv", sep = '\t', encoding = "latin-1")
    df.to_csv(f"{search}/wos/wos_{x}.csv", encoding = "utf-8", sep = ",", index = False)
    globals()[f"wos_{x}"] = df
    
import pandas as pd 
search = f"./systematic_review/search"

databases = {"pm": "pubmed", 
             "em": "embase", 
             "wos": "wos"}

subgroups = {"bptb": "patellar", 
             "ht": "hamstring", 
             "qt": "quadriceps", 
             "plt": "peroneus", 
             "at": "achilles", 
             "ta": "tibialis"}


# Create pubmed.csv, embase.csv, and wos.csv
for a, b in databases.items():
    dfs = []
    for x, y in subgroups.items():
        df = pd.read_csv(f"{search}/{b}/{a}_{x}.csv", encoding = "utf-8")
        df['source'] = b
        df['subgroup'] = x
        dfs.append(df)
        globals()[f"{a}_{x}"] = df
        data = pd.concat(dfs, ignore_index = True)
        data.insert(0, "id", range(1, len(data) + 1))
        data.to_csv(f"{search}/{b}/{b}.csv", encoding = "utf-8", index = False)
        globals()[f"{b}"] = data

databases = {"pm": "pubmed", 
             "em": "embase", 
             "wos": "wos"}

subgroups = {"bptb": "patellar", 
             "ht": "hamstring", 
             "qt": "quadriceps", 
             "plt": "peroneus", 
             "at": "achilles", 
             "ta": "tibialis"}

lengths = []
data = []
for a, b in databases.items():
    for c, d in subgroups.items():
        df = globals()[f"{a}_{c}"]
        length = len(df)
        datum = [b, d, length]
        lengths.append(length)
        data.append(datum)

data = pd.DataFrame(data, columns = ["source", "subgroup", "k"])
data.to_csv("./number_results.csv", encoding = "utf-8")

embase.rename(columns = {
	"Title" : "title",
	"Original Title" : "original_title",
	"Author Names" : "authors",
	"Author Addresses" : "author_addresses",
	"Correspondence Address" : "correspondence_address",
	"Editors" : "editors",
	"AiP/IP Entry Date" : "aip/ip_entry_date",
	"Full Record Entry Date" : "full_record_entry_date",
	"Source" : "journal_abbr",
	"Source title" : "journal_full",
	"Publication Year" : "year",
	"Volume" : "volume",
	"Issue" : "issue",
	"First Page" : "first_page",
	"Last Page" : "last_page",
	"Date of Publication" : "date",
	"Publication Type" : "study_design",
	"Conference Name" : "conference_name",
	"Conference" : "conference",
	"Conference" : "conference",
	"Conference" : "conference",
	"ISSN" : "issn",
	"ISBN" : "isbn",
	"Name" : "name",
	"Location" : "location",
	"Date" : "date",
	"Editors" : "editors",
	"Book Publisher" : "book_publisher",
	"Abstract" : "abstract",
	"Original Abstract" : "original_abstract",
	"Author Keywords" : "author_keywords",
	"Emtree Drug Index Terms (Major Focus)" : "emtree_drug_index_terms_(major_focus)",
	"Emtree Drug Index Terms" : "emtree_drug_index_terms",
	"Emtree Medical Index Terms (Major Focus)" : "emtree_medical_index_terms_(major_focus)",
	"Emtree Medical Index Terms" : "emtree_medical_index_terms",
	"Drug Tradenames" : "drug_tradenames",
	"Drug Manufacturer" : "drug_manufacturer",
	"Device Tradenames" : "device_tradenames",
	"Device Manufacturer" : "device_manufacturer",
	"CAS Registry Numbers" : "cas_registry_numbers",
	"Molecular Sequence Numbers" : "molecular_sequence_numbers",
	"Embase Classification" : "embase_classification",
	"Clinical Trial Numbers" : "clinical_trial_numbers",
	"Article Language" : "article_language",
	"Summary Language" : "summary_language",
	"Embase Accession ID" : "embase_accession_id",
	"Medline PMID" : "pmid",
	"PUI" : "pui",
	"DOI" : "doi",
	"Full Text Link" : "full_text_link",
	"Embase Link" : "embase_link",
	"Open IJRL Link" : "open_ijrl_link",
	"Copyright" : "copyright",
	"source" : "source",
	"subgroup" : "subgroup"
}, inplace = True)

pubmed.rename(columns = {
	"id" : "id",
	"pmid" : "pmid",
	"PubDate" : "date",
	"EPubDate" : "epubdate",
	"Source" : "journal_abbr",
	"AuthorList" : "authors",
	"LastAuthor" : "last_author",
	"Title" : "title",
	"Volume" : "volume",
	"Issue" : "issue",
	"Pages" : "pages",
	"LangList" : "language",
	"NlmUniqueID" : "nlmuniqueid",
	"ISSN" : "issn",
	"ESSN" : "essn",
	"PubTypeList" : "study_design",
	"RecordStatus" : "recordstatus",
	"PubStatus" : "pubstatus",
	"Articlelds" : "articlelds",
	"DOI" : "doi",
	"History" : "history",
	"References" : "references",
	"HasAbstract" : "hasabstract",
	"PmcRefCount" : "pmcrefcount",
	"FullJournalName" : "journal_full",
	"ELocationID" : "elocationid",
	"SO" : "so",
	"abstract" : "abstract",
	"source" : "source",
	"subgroup" : "subgroup"
}, inplace = True)

wos.rename(columns = {
    "id": "id",
	"ï»¿PT" : "study_design",
	"AU" : "authors",
	"BA" : "book_authors",
	"BE" : "book_editors",
	"GP" : "book_group_authors",
	"AF" : "authors_full",
	"BF" : "book_author_full_names",
	"CA" : "group_authors",
	"TI" : "title",
	"SO" : "journal_full",
	"SE" : "book_series_title",
	"BS" : "book_series_subtitle",
	"LA" : "language",
	"DT" : "document_type",
	"CT" : "conference_title",
	"CY" : "conference_date",
	"CL" : "conference_location",
	"SP" : "conference_sponsor",
	"HO" : "conference_host",
	"DE" : "author_keywords",
	"ID" : "keywords_plus",
	"AB" : "abstract",
	"C1" : "addresses",
	"C3" : "affiliations",
	"RP" : "reprint_addresses",
	"EM" : "email_addresses",
	"RI" : "researcher_ids",
	"OI" : "orcids",
	"FU" : "funding_orgs",
	"FP" : "funding_name_preferred",
	"FX" : "funding_text",
	"CR" : "cited_references",
	"NR" : "cited_reference_count",
	"TC" : "times_cited, wos_core",
	"Z9" : "times_cited, all_databases",
	"U1" : "180_day_usage_count",
	"U2" : "since_2013_usage_count",
	"PU" : "publisher",
	"PI" : "publisher_city",
	"PA" : "publisher_address",
	"SN" : "issn",
	"EI" : "eissn",
	"BN" : "isbn",
	"J9" : "journal_abbr",
	"JI" : "journal_iso_abbreviation",
	"PD" : "date",
	"PY" : "year",
	"VL" : "volume",
	"IS" : "issue",
	"PN" : "part_number",
	"SU" : "supplement",
	"SI" : "special_issue",
	"MA" : "meeting_abstract",
	"BP" : "start_page",
	"EP" : "end_page",
	"AR" : "article_number",
	"DI" : "doi",
	"DL" : "doi_link",
	"D2" : "book_doi",
	"EA" : "early_access_date",
	"PG" : "number_of_pages",
	"WC" : "wos_categories",
	"WE" : "web_of_science_index",
	"SC" : "research_areas",
	"GA" : "ids_number",
	"PM" : "pmid",
	"OA" : "open_access_designations",
	"HC" : "highly_cited_status",
	"HP" : "hot_paper_status",
	"DA" : "date_of_export",
	"UT" : "ut (unique_wos_id)",
	"source" : "source",
    "subgroup": "subgroup"
}, inplace = True)

pubmed.to_csv(f"{search}/pubmed.csv", encoding = "utf-8")
embase.to_csv(f"{search}/embase.csv", encoding = "utf-8")
wos.to_csv(f"{search}/wos.csv", encoding = "latin-1")

pubmed = pd.DataFrame({
    "id": pubmed['id'],
    "source": pubmed['source'],
    "subgroup": pubmed['subgroup'],
    'doi': pubmed['doi'],
    'authors': pubmed['authors'],
    'journal': pubmed['journal_abbr'],
    'title': pubmed['title'],
    'abstract': pubmed['abstract'],
    'year': pubmed['year']
})

embase = pd.DataFrame({
    "id": embase['id'],
    "source": embase['source'],
    "subgroup": embase['subgroup'],
    'doi': embase['doi'],
    'authors': embase['authors'],
    'journal': embase['journal_abbr'],
    'title': embase['title'],
    'abstract': embase['abstract'],
    'year': embase['year']
})

wos = pd.DataFrame({
    "id": wos['id'],
    "source": wos['source'],
    "subgroup": wos['subgroup'],
    'authors': wos['authors'],
    'doi': wos['doi'],
    'journal': wos['journal_abbr'],
    'title': wos['title'],
    'abstract': wos['abstract'],
    'year': wos['year']
})

pubmed.info()
pubmed.head()
embase.info()
embase.head()
wos.info()
wos.head()

records = pd.concat([pubmed, embase, wos])
records['first_author'] = records['authors'].str.replace(r"[\'\[\],.;]",'', regex = True).str.split().str[0]
records['short_title'] = records['title'].str.replace(r'[\[\]\s,.;-]','',regex = True).str.lower().str[:30]
records['key'] = records['first_author'] + '+' + records['short_title'] + '+' + records['year'].astype(str)
records.to_csv(f"{search}/records.csv", encoding = "utf-8")
records.to_csv(f"{deduplication}/records.csv", encoding = "utf-8")

<class 'pandas.DataFrame'>
RangeIndex: 573 entries, 0 to 572
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        573 non-null    int64
 1   source    573 non-null    str
 2   subgroup  573 non-null    str
 3   doi       525 non-null    str
 4   authors   573 non-null    str
 5   journal   573 non-null    str
 6   title     573 non-null    str
 7   abstract  573 non-null    str
 8   year      573 non-null    int64
dtypes: int64(2), str(7)
memory usage: 40.4 KB
<class 'pandas.DataFrame'>
RangeIndex: 317 entries, 0 to 316
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        317 non-null    int64
 1   source    317 non-null    str
 2   subgroup  317 non-null    str
 3   doi       207 non-null    str
 4   authors   228 non-null    str
 5   journal   317 non-null    str
 6   title     317 non-null    str
 7   abstract  315 non-null    str
 8   year      317 non-null    int64
dtypes: int64(2), str(7)
memory usage: 22.4 KB
<class 'pandas.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        531 non-null    int64
 1   source    531 non-null    str
 2   subgroup  531 non-null    str
 3   authors   531 non-null    str
 4   doi       524 non-null    str
 5   journal   531 non-null    str
 6   title     531 non-null    str
 7   abstract  521 non-null    str
 8   year      531 non-null    int64
dtypes: int64(2), str(7)
memory usage: 37.5 KB

[previous](#search) | [top](#toc) | [next](#screening)  
[search strategy](#search-strategy) | [search](#search) | [deduplication](#deduplication) | [screening](#screening)

<a id="deduplication"></a>
<div align="center">
	<font size="5" style="font-family:Times New Roman;font-variant: small-caps;">Deduplication</font><br>
</div>

In [47]:
import pandas as pd
import mermaid
import os

input_file_name = f"{deduplication}/" + input('Enter file name: ') + '.csv'
df = pd.read_csv(input_file_name) # A (records)
cols_input = input('Enter the column for which to deduplicate based on: ')
cols = [c.strip() for c in cols_input.split(',')]
folder = '_'.join(cols)
os.makedirs(f"{deduplication}/{folder}/", exist_ok = True)

output_file = f"{deduplication}/{folder}/{folder}_deduplicated"
output_file_name = f"{output_file}.csv"
output_for_recycle = f"{deduplication}/{folder}_deduplicated.csv"
prisma_file_name = f"{output_file}.mmd"

nulls_mask = df[cols].isnull().any(axis=1)
df_nulls = df[nulls_mask] # B
df_non_nulls = df[~nulls_mask] # C

duplicates_mask = df_non_nulls.duplicated(subset = cols, keep = False)
df_non_duplicates = df_non_nulls[~duplicates_mask] # D
df_duplicates = df_non_nulls[duplicates_mask] # E
df_kept = df_duplicates.drop_duplicates(subset = cols, keep = 'first')
df_removed = df_duplicates[~df_duplicates.index.isin(df_kept.index)]
df_unique = df_non_nulls.drop_duplicates(subset = cols, keep = 'first') # df of unique
df_deduplicated = pd.concat([df_non_duplicates, df_kept, df_nulls], ignore_index=True) # df of unique + df of non-duplicates

results = {"records": len(df),  
"nulls": len(df_nulls), 
"non_nulls": len(df_non_nulls), 
"non_duplicates": len(df_non_duplicates), 
"duplicates": len(df_duplicates), 
"removed": len(df_removed), 
"kept": len(df_kept),
"unique": len(df_unique),
"deduplicated": len(df_deduplicated)
}

print(results)

# output_file_name = deduplication/doi/doi_deduplicated.csv
df_nulls.to_csv(output_file_name.replace('deduplicated','nulls'), index = False)
df_deduplicated.to_csv(output_file_name, index = False)
df_removed.to_csv(output_file_name.replace('deduplicated','duplicates_removed'), index = False)
df_nulls.to_csv(output_file_name.replace('deduplicated','nulls'), index = False)
df_deduplicated.to_csv(output_for_recycle, index = False)

graph_text = f"""---
config:
theme: neutral
curve: stepBefore
---
graph TD;
A["`**records** (*n* = {results['records']})`"];
B["`null (*n* = {results['nulls']})`"];
C["`non-null (*n* = {results['non_nulls']})`"];
D["`non-duplicates (*n* = {results['non_duplicates']})`"];
E["`duplicates (*n* = {results['duplicates']})`"];
F["`duplicates kept (*n* = {results['kept']})`"];
G["`duplicates removed (*n* = {results['removed']})`"];
H["`unique (*n* = {results['unique']})`"];
I["`deduplicated (*n* = {results['deduplicated']})`"];

A --> B & C;
C --> D & E;
E --> F & G;
D & F --> H
B & H --> I"""

with open(prisma_file_name, "w") as f:
    f.write(graph_text)

!mmdc -i {prisma_file_name} -o {output_file}.svg
!mmdc -i {prisma_file_name} -o {output_file}_dark.svg -t dark -b transparent

Enter file name:  doi_deduplicated
Enter the column for which to deduplicate based on:  key

{'records': 818, 'nulls': 88, 'non_nulls': 730, 'non_duplicates': 650, 'duplicates': 80, 'removed': 45, 'kept': 35, 'unique': 685, 'deduplicated': 773}
Generating single mermaid chart
Generating single mermaid chart

In [43]:
records.head()

,id,source,subgroup,doi,authors,journal,title,abstract,year,first_author,short_title,key
0,1,pubmed,bptb,10.1177/03635465251328609,"['Rao N', 'Triana J', 'Avila A', 'Campbell KA'...",Am J Sports Med,Postoperative Pain and Opioid Usage With Combi...,"BACKGROUND: Efforts to decrease pain, improve ...",2025,Rao,postoperativepainandopioidusag,Rao+postoperativepainandopioidusag+2025
1,2,pubmed,bptb,10.1002/ksa.12449,"['Martorell-de Fortuny L', 'Torres-Claramunt R...",Knee Surg Sports Traumatol Arthrosc,Patellar bone defect grafting does not reduce ...,PURPOSE: Donor site morbidity is the main draw...,2025,Martorell-de,patellarbonedefectgraftingdoes,Martorell-de+patellarbonedefectgraftingdoes+2025
2,3,pubmed,bptb,10.1002/ksa.12031,"['Martin RK', 'Marmura H', 'Wastvedt S', 'Pare...",Knee Surg Sports Traumatol Arthrosc,External validation of the Norwegian anterior ...,PURPOSE: A machine learning-based anterior cru...,2024,Martin,externalvalidationofthenorwegi,Martin+externalvalidationofthenorwegi+2024
3,4,pubmed,bptb,10.3390/medicina59101764,"['Obradović M', 'Ninković S', 'Gvozdenović N',...",Medicina (Kaunas),Tubularization of Bone-Tendon-Bone Grafts: Eff...,Background and Objectives: The study addresses...,2023,Obradović,tubularizationofbonetendonbone,Obradović+tubularizationofbonetendonbone+2023
4,5,pubmed,bptb,10.1177/19417381221101006,"['Jack RA 2nd', 'Lambert BS', 'Hedt CA', 'Delg...",Sports Health,Blood Flow Restriction Therapy Preserves Lower...,BACKGROUND: Muscle atrophy is common after an ...,2023,Jack,bloodflowrestrictiontherapypre,Jack+bloodflowrestrictiontherapypre+2023

[previous](#deduplication) | [top](#toc) | [next](#data_collection)  
[search strategy](#search-strategy) | [search](#search) | [deduplication](#deduplication) | [screening](#screening)

<a id="screening"></a>
<div align="center">
	<font size="5" style="font-family:Times New Roman;font-variant: small-caps;">Screening</font><br>
</div>

---

In [ ]:
key_deduplicated = pd.read_csv(f"{deduplication}/key_deduplicated.csv", encoding = "utf-8")
screening = key_deduplicated
screening["study"] = screening['first_author'] + " " + screening['year'].astype(str)


tiab = pd.DataFrame({
    "id": screening["id"],
    "study": screening["study"],
    "doi": screening["doi"],
    "title": screening["title"],
    "abstract": screening["abstract"],
    "url": f"https://doi.org/" + screening["doi"],
    "subgroup": screening["subgroup"],
    "year": screening["year"],
    "journal": screening["journal"]
})

tiab = tiab[["id", "study", "subgroup", "title", "abstract", "year", "doi", "url"]]
tiab['title_abstract_screening'] = 'yes'
tiab.head()

tiab.to_csv(f"{title_abstract}/title_abstract_screening.csv", encoding = "utf-8")

<a id="screening"></a>
<div align="center">
	<font size="5" style="font-family:Times New Roman;font-variant: small-caps;">patellar</font><br>
</div>

In [113]:
patellar = tiab[tiab["subgroup"] == "bptb"]
patellar.to_csv(f"{title_abstract}/patellar.csv", encoding = "utf-8")